name: github_search
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  async: ^2.5.0
  redux_epics: ^0.15.0
  rxdart: ^0.26.0
  transparent_image: ^2.0.0
  flutter_svg: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  flutter_launcher_icons: "^0.9.2"


  flutter_lints: ^1.0.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Octocat.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Bold.ttf
        - asset: fonts/montserrat/Montserrat-Regular.ttf
    - family: Hind
      fonts:
        - asset: fonts/hind/Hind-Regular.ttf
