name: flutter_samples
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  map: ^1.3.0
  cached_network_image: ^3.2.0
  starflut: ^0.9.5
  flutter_google_street_view: ^2.2.7
  flextras: ^0.0.2
  pointer_interceptor: ^0.9.3+2
  image_picker: ^0.8.5+3
  animated_splash_screen: ^1.3.0

  cupertino_icons: ^1.0.2
  animated_theme_switcher: ^2.0.6
  mrx_charts: ^0.1.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: "assets/sample.png" 
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ff4bb4a2"
  adaptive_icon_foreground: assets/sample.png

flutter:

  uses-material-design: true
