name: better_buys
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: assets/icon.jpg 
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ff4bb4a2"
  adaptive_icon_foreground: assets/icon.jpg

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
